def remove():
    return {'PATIENT': '',
            'STAFF': '',
            'AGE': '',
            'DATE': '',
            'PHONE': '',
            'MRN': '',
            'ID': '',
            'EMAIL': '',
            'PATORG': '',
            'LOC': '',
            'HOSP': '',
            'OTHERPHI': ''}


def replace_tag_type():
    return {'PATIENT': 'PATIENT',
            'STAFF': 'STAFF',
            'AGE': 'AGE',
            'DATE': 'DATE',
            'PHONE': 'PHONE',
            'MRN': 'MRN',
            'ID': 'ID',
            'EMAIL': 'EMAIL',
            'PATORG': 'PATORG',
            'LOC': 'LOCATION',
            'HOSP': 'HOSPITAL',
            'OTHERPHI': 'OTHERPHI'}


def replace_informative():
    return {'PATIENT': '<<PATIENT:{}>>',
            'STAFF': '<<STAFF:{}>>',
            'AGE': '<<AGE:{}>>',
            'DATE': '<<DATE:{}>>',
            'PHONE': '<<PHONE:{}>>',
            'MRN': '<<MRN:{}>>',
            'ID': '<<ID:{}>>',
            'EMAIL': '<<EMAIL:{}>>',
            'PATORG': '<<PATORG:{}>>',
            'LOC': '<<LOCATION:{}>>',
            'HOSP': '<<HOSPITAL:{}>>',
            'OTHERPHI': '<<OTHERPHI:{}>>'}

def retain_informative():
    return {'URL': '<<URL:{}>>',
            'TIME': '<<TIME:{}>>',
            'PHONE': '<<PHONE:{}>>',
            'STREET': '<<STREET:{}>>',
            'SET': '<<SET:{}>>',
            'MEDICALRECORD': '<<MEDICALRECORD:{}>>',
            'PATIENT': '<<PATIENT:{}>>',
            'STATE': '<<STATE:{}>>',
            'DEPARTMENT': '<<DEPARTMENT:{}>>',
            'DOCTOR': '<<DOCTOR:{}>>',
            'ORGANIZATION': '<<ORGANIZATION:{}>>',
            'DATE': '<<DATE:{}>>',
            'HOSPITAL': '<<HOSPITAL:{}>>',
            'LOCATION-OTHER': '<<LOCATION-OTHER:{}>>',
            'IDNUM': '<<IDNUM:{}>>',
            'CITY': '<<CITY:{}>>',
            'COUNTRY': '<<COUNTRY:{}>>',
            'ZIP': '<<ZIP:{}>>',
            'DURATION': '<<DURATION:{}>>',
            'AGE': '<<AGE:{}>>',
            }
def retain_informative_i2b2():
    return {
        'DOCTOR': '<<DOCTOR:>>',
        'DATE': '<<DATE:>>',
        'IDNUM': '<<IDNUM:>>',
        'MEDICALRECORD': '<<MEDICALRECORD:>>',
        'PATIENT': '<<PATIENT:>>',
        'HOSPITAL': '<<HOSPITAL:>>',
        'TIME': '<<TIME:>>',
        'DEPARTMENT': '<<DEPARTMENT:>>',
        'CITY': '<<CITY:>>',
        'ZIP': '<<ZIP:>>',
        'STREET': '<<STREET:>>',
        'STATE': '<<STATE:>>',
        'ORGANIZATION': '<<ORGANIZATION:>>',
        'AGE': '<<AGE:>>',
        'DURATION': '<<DURATION:>>',
        'SET': '<<SET:>>',
        'PHONE': '<<PHONE:>>',
        'LOCATION-OTHER': '<<LOCATION-OTHER:>>',
        'COUNTRY': '<<COUNTRY:>>',
        'URL': '<<URL:>>',
        'ROOM': '<<ROOM:>>',
        'USERNAME': '<<USERNAME:>>',
        'PROFESSION': '<<PROFESSION:>>',
        'FAX': '<<FAX:>>',
        'DEVICE': '<<DEVICE:>>',
        'EMAIL': '<<EMAIL:>>',
        'BIOID': '<<BIOID:>>',
        'HEALTHPLAN': '<<HEALTHPLAN:>>'
    }